FROM node:25-alpine3.23

# from https://github.com/docker-library/postgres/blob/master/18/alpine3.23/Dockerfile
RUN set -eux; \
    addgroup -g 70 -S postgres; \
    adduser -u 70 -S -D -G postgres -H -h /var/lib/postgresql -s /bin/sh postgres; \
    install --verbose --directory --owner postgres --group postgres --mode 1777 /var/lib/postgresql

ENV GOSU_VERSION=1.19
RUN set -eux; \
    \
    apk add --no-cache --virtual .gosu-deps \
        ca-certificates \
        dpkg \
        gnupg \
    ; \
    \
    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
    gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
    gpgconf --kill all; \
    rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
    \
    apk del --no-network .gosu-deps; \
    \
    chmod +x /usr/local/bin/gosu; \
    gosu --version; \
    gosu nobody true

    ENV LANG=en_US.utf8

    RUN mkdir /docker-entrypoint-initdb.d

    ENV PG_MAJOR=18
    ENV PG_VERSION=18.3
    ENV PG_SHA256=d95663fbbf3a80f81a9d98d895266bdcb74ba274bcc04ef6d76630a72dee016f

    ENV DOCKER_PG_LLVM_DEPS="llvm19-dev clang19"
    
    RUN set -eux; \
        \
        wget -O postgresql.tar.bz2 "https://ftp.postgresql.org/pub/source/v$PG_VERSION/postgresql-$PG_VERSION.tar.bz2"; \
        echo "$PG_SHA256 *postgresql.tar.bz2" | sha256sum -c -; \
        mkdir -p /usr/src/postgresql; \
        tar \
            --extract \
            --file postgresql.tar.bz2 \
            --directory /usr/src/postgresql \
            --strip-components 1 \
        ; \
        rm postgresql.tar.bz2; \
        \
        apk add --no-cache --virtual .build-deps \
            $DOCKER_PG_LLVM_DEPS \
            bison \
            coreutils \
            dpkg-dev dpkg \
            flex \
            g++ \
            gcc \
            krb5-dev \
            libc-dev \
            libedit-dev \
            libxml2-dev \
            libxslt-dev \
            linux-headers \
            make \
            openldap-dev \
            openssl-dev \
            perl-dev \
            perl-ipc-run \
            perl-utils \
            python3-dev \
            tcl-dev \
            util-linux-dev \
            zlib-dev \
            icu-dev \
            lz4-dev \
            zstd-dev \
            curl-dev \
            liburing-dev \
      ; \
      \
      cd /usr/src/postgresql; \
      awk '$1 == "#define" && $2 == "DEFAULT_PGSOCKET_DIR" && $3 == "\"/tmp\"" { $3 = "\"/var/run/postgresql\""; print; next } { print }' src/include/pg_config_manual.h > src/include/pg_config_manual.h.new; \
      grep '/var/run/postgresql' src/include/pg_config_manual.h.new; \
      mv src/include/pg_config_manual.h.new src/include/pg_config_manual.h; \
      gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
      \
      export LLVM_CONFIG="/usr/lib/llvm19/bin/llvm-config"; \
      export CLANG=clang-19; \
      \
      ./configure \
          --enable-option-checking=fatal \
          --build="$gnuArch" \
          --enable-integer-datetimes \
          --enable-tap-tests \
          --disable-rpath \
          --with-uuid=e2fs \
          --with-pgport=5432 \
          --with-system-tzdata=/usr/share/zoneinfo \
          --prefix=/usr/local \
          --with-includes=/usr/local/include \
          --with-libraries=/usr/local/lib \
          --with-gssapi \
          --with-icu \
          --with-ldap \
          --with-libcurl \
          --with-liburing \
          --with-libxml \
          --with-libxslt \
          --with-llvm \
          --with-lz4 \
          --with-openssl \
          --with-perl \
          --with-python \
          --with-tcl \
          --with-zstd \
    ; \
    make -j "$(nproc)" world-bin; \
    make install-world-bin; \
    make -C contrib install; \
    \
    runDeps="$(\
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
            | grep -v -e perl -e python -e tcl \
    )"; \
    apk add --no-cache --virtual .postgresql-rundeps \
        $runDeps \ 
        bash \
        tzdata \
        zstd \
        icu-data-full \
        $([ "$(apk --print-arch)" != 'ppc64le' ] && echo 'nss_wrapper') \
    ; \
    apk del --no-network .build-deps; \
    cd /; \
    rm -rf \
        /usr/src/postgresql \
        /usr/local/share/doc \
        /usr/local/share/man \
    ; \
    \
    postgres --version

RUN set -eux; \
    cp -v /usr/local/share/postgresql/postgresql.conf.sample /usr/local/share/postgresql/postgresql.conf.sample.orig; \
    sed -ri "s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '*'!" /usr/local/share/postgresql/postgresql.conf.sample; \
    grep -F "listen_addresses = '*'" /usr/local/share/postgresql/postgresql.conf.sample

RUN install --verbose --directory --owner postgres --group postgres --mode 3777 /var/run/postgresql

ENV PGDATA=/var/lib/postgresql/18/docker
VOLUME /var/lib/postgresql

# COPY docker-entrypoint.sh docker-ensure-initdb.sh /usr/local/bin/ 
# We need to modify the entrypoint to ensure that the initdb script is fetch from the official postgres image
RUN set -eux; \
    wget -O /usr/local/bin/docker-entrypoint.sh "https://raw.githubusercontent.com/docker-library/postgres/master/18/alpine3.23/docker-entrypoint.sh"; \
    wget -O /usr/local/bin/docker-ensure-initdb.sh "https://raw.githubusercontent.com/docker-library/postgres/master/18/alpine3.23/docker-ensure-initdb.sh"; \
    chmod +x /usr/local/bin/docker-entrypoint.sh /usr/local/bin/docker-ensure-initdb.sh

RUN ln -sT docker-ensure-initdb.sh /usr/local/bin/docker-enforce-initdb.sh
ENTRYPOINT ["docker-entrypoint.sh"]

STOPSIGNAL SIGINT

EXPOSE 5432
CMD ["postgres"]


