export enum Resource {
  User = 'user',
  Role = 'role',
  Permission = 'permission',
  Group = 'group',
  Document = 'document',
  Report = 'report',
  Dashboard = 'dashboard',
  Configuration = 'configuration',
  Secret = 'secret',
  ApiKey = 'api-key',
  Billing = 'billing',
  Invoice = 'invoice',
  Subscription = 'subscription',
  Project = 'project',
  Task = 'task',
  Comment = 'comment',
  Log = 'log',
  AuditTrail = 'audit-trail',
  Webhook = 'webhook',
  Notification = 'notification',
  Integration = 'integration',
}
